export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const DATA_LOADED = "DATA_LOADED";
export const UPDATE_HEADER = "UPDATE_HEADER";
export const UPDATE_DELIMITER = "UPDATE_DELIMITER";
export const UPDATE_DECIMAL = "UPDATE_DECIMAL";
export const SET_CHART = "SET_CHART";